[tool.pyflow]
name = "turvallisuusneuvonta"
py_version = "3.8"
version = "2022.2.14"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]

[tool.pyflow.dev-dependencies]
