# generated by datamodel-codegen:
#   filename:  csaf_2_0.json
#   timestamp: 2021-12-29T15:01:38+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated, Optional

from pydantic import BaseModel, Field

from . import (
    AttackComplexityType,
    AttackComplexityTypeModel,
    AttackVectorType,
    AttackVectorTypeModel,
    CiaRequirementTypeModel,
    CiaRequirementTypeModel1,
    CiaTypeModel,
    CiaTypeModel1,
    ConfidenceType,
    ConfidenceTypeModel,
    ExploitCodeMaturityType,
    ExploitCodeMaturityTypeModel,
    ModifiedAttackComplexityType,
    ModifiedAttackComplexityTypeModel,
    ModifiedAttackVectorType,
    ModifiedAttackVectorTypeModel,
    ModifiedCiaType,
    ModifiedCiaTypeModel,
    ModifiedPrivilegesRequiredType,
    ModifiedPrivilegesRequiredTypeModel,
    ModifiedScopeType,
    ModifiedScopeTypeModel,
    ModifiedUserInteractionType,
    ModifiedUserInteractionTypeModel,
    PrivilegesRequiredType,
    PrivilegesRequiredTypeModel,
    RemediationLevelTypeModel,
    RemediationLevelTypeModel1,
    ScopeType,
    ScopeTypeModel,
    ScoreTypeModel,
    ScoreTypeModel1,
    SeverityType,
    SeverityTypeModel,
    UserInteractionType,
    UserInteractionTypeModel,
)


class Version(Enum):
    field_3_0 = '3.0'


class VersionModel(Enum):
    field_3_1 = '3.1'


class Field0(BaseModel):
    version: Annotated[Version, Field(description='CVSS Version')]
    vectorString: Annotated[
        str,
        Field(
            regex=(
                '^CVSS:3[.]0/((AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|'
                'RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*'
                '(AV:[NALP]|AC:[LH]|PR:[UNLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|'
                'RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XUNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$'
            )
        ),
    ]
    attackVector: Optional[AttackVectorType] = None
    attackComplexity: Optional[AttackComplexityType] = None
    privilegesRequired: Optional[PrivilegesRequiredType] = None
    userInteraction: Optional[UserInteractionType] = None
    scope: Optional[ScopeType] = None
    confidentialityImpact: Optional[CiaTypeModel] = None
    integrityImpact: Optional[CiaTypeModel] = None
    availabilityImpact: Optional[CiaTypeModel] = None
    baseScore: ScoreTypeModel
    baseSeverity: SeverityType
    exploitCodeMaturity: Optional[ExploitCodeMaturityType] = None
    remediationLevel: Optional[RemediationLevelTypeModel] = None
    reportConfidence: Optional[ConfidenceType] = None
    temporalScore: Optional[ScoreTypeModel] = None
    temporalSeverity: Optional[SeverityType] = None
    confidentialityRequirement: Optional[CiaRequirementTypeModel] = None
    integrityRequirement: Optional[CiaRequirementTypeModel] = None
    availabilityRequirement: Optional[CiaRequirementTypeModel] = None
    modifiedAttackVector: Optional[ModifiedAttackVectorType] = None
    modifiedAttackComplexity: Optional[ModifiedAttackComplexityType] = None
    modifiedPrivilegesRequired: Optional[ModifiedPrivilegesRequiredType] = None
    modifiedUserInteraction: Optional[ModifiedUserInteractionType] = None
    modifiedScope: Optional[ModifiedScopeType] = None
    modifiedConfidentialityImpact: Optional[ModifiedCiaType] = None
    modifiedIntegrityImpact: Optional[ModifiedCiaType] = None
    modifiedAvailabilityImpact: Optional[ModifiedCiaType] = None
    environmentalScore: Optional[ScoreTypeModel] = None
    environmentalSeverity: Optional[SeverityType] = None


class Field1(BaseModel):
    version: Annotated[VersionModel, Field(description='CVSS Version')]
    vectorString: Annotated[
        str,
        Field(
            regex=(
                '^CVSS:3[.]1/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|'
                'RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*'
                '(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|'
                'RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$'
            )
        ),
    ]
    attackVector: Optional[AttackVectorTypeModel] = None
    attackComplexity: Optional[AttackComplexityTypeModel] = None
    privilegesRequired: Optional[PrivilegesRequiredTypeModel] = None
    userInteraction: Optional[UserInteractionTypeModel] = None
    scope: Optional[ScopeTypeModel] = None
    confidentialityImpact: Optional[CiaTypeModel1] = None
    integrityImpact: Optional[CiaTypeModel1] = None
    availabilityImpact: Optional[CiaTypeModel1] = None
    baseScore: ScoreTypeModel1
    baseSeverity: SeverityTypeModel
    exploitCodeMaturity: Optional[ExploitCodeMaturityTypeModel] = None
    remediationLevel: Optional[RemediationLevelTypeModel1] = None
    reportConfidence: Optional[ConfidenceTypeModel] = None
    temporalScore: Optional[ScoreTypeModel1] = None
    temporalSeverity: Optional[SeverityTypeModel] = None
    confidentialityRequirement: Optional[CiaRequirementTypeModel1] = None
    integrityRequirement: Optional[CiaRequirementTypeModel1] = None
    availabilityRequirement: Optional[CiaRequirementTypeModel1] = None
    modifiedAttackVector: Optional[ModifiedAttackVectorTypeModel] = None
    modifiedAttackComplexity: Optional[ModifiedAttackComplexityTypeModel] = None
    modifiedPrivilegesRequired: Optional[ModifiedPrivilegesRequiredTypeModel] = None
    modifiedUserInteraction: Optional[ModifiedUserInteractionTypeModel] = None
    modifiedScope: Optional[ModifiedScopeTypeModel] = None
    modifiedConfidentialityImpact: Optional[ModifiedCiaTypeModel] = None
    modifiedIntegrityImpact: Optional[ModifiedCiaTypeModel] = None
    modifiedAvailabilityImpact: Optional[ModifiedCiaTypeModel] = None
    environmentalScore: Optional[ScoreTypeModel1] = None
    environmentalSeverity: Optional[SeverityTypeModel] = None
